baseURL: www.example.com
languageCode: es
title: AboSex
theme: hugo-serif-theme
enableGitInfo: true
taxonomies:
  tag: tags
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  footer:
    copyright_text: Web creada con el soporte de Hugo, y del tema Serif, creado por <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>
  google_analytics_id: ''
  google_tag_manager_id: ''
  homepage:
    show_contact_box: no
    show_services_button: no
  logo:
    alt: AboSex - Abogados por los Derechos Sexuales
    desktop: images/logo/logo.svg
    desktop_height: 36px
    mobile: images/logo/logo_mobile.svg
    mobile_height: 36px
  seo:
    meta_twitter_creator: '@AboSex_ar'
    meta_twitter_site: '@AboSex_ar'
  team:
    summary_large_truncate: 500
menu:
  footer:
    - name: Home
      url: /
      weight: 1
    - name: Contacto
      url: /contact/
      weight: 2
  main:
    - name: Hacemos
      url: /services/
      weight: 3
    - name: Equipo
      url: /team/
      weight: 2
    - name: Somos
      url: /about/
      weight: 1
    - name: Contacto
      url: /contact/
      weight: 5
    - name: Decimos
      url: /post/
      weight: 4
